In [7]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.datasets import load_iris

In [8]:
data= load_iris()
X= data.data
y= data.target


In [16]:
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.35, random_state=42)

In [17]:
scaler = StandardScaler()
X_train= scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


In [18]:
knn= KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train,y_train)
y_pred= knn.predict(X_test)
accuracy= accuracy_score(y_test,y_pred)
print(accuracy)

0.9811320754716981


In [19]:
conf= confusion_matrix(y_test,y_pred)

In [20]:
print(conf)

[[19  0  0]
 [ 0 17  0]
 [ 0  1 16]]
