In [1]:
import pandas as pd
import numpy as np
customers_df = pd.read_csv("customers.csv")
orders_df = pd.read_csv("orders.csv")
products_df = pd.read_csv("products.csv")

In [2]:
print("Coustomer details: \n")
customers_df

Coustomer details: 



customer_id     name   age              email
0            1  Murshid  30.0  murshid@gmail.com
1            2     Prem  25.0     prem@gmail.com
2            3      Jon  40.0      jon@gmail.com
3            4    Rahul   NaN    rahul@gmail.com
4            5     Adil  35.0                NaN

In [3]:
print("Order details: \n")
orders_df

Order details: 



order_id  customer_id  product_id  quantity
0       101            1         201         2
1       102            2         202         1
2       103            3         203         3
3       104            4         204         2
4       105            5         205         1

In [4]:
print("Product details: \n")
products_df

Product details: 



product_id product_name  price
0         201       Laptop   1000
1         202        Mouse     20
2         203     Keyboard     50
3         204      Monitor    300
4         205      Printer    200

In [5]:
customers_df['age'].fillna(customers_df['age'].mean(), inplace=True)
customers_df['email'].fillna('N/A', inplace=True)

merged_df = pd.merge(pd.merge(customers_df, orders_df, on='customer_id'), products_df, on='product_id')
merged_df['total_price'] = merged_df['quantity'] * merged_df['price']
merged_df['Feed_back'] = np.where(merged_df['quantity']>1, "Good", "Bad")

print("Cleaned, Integrated, and Transformed Data:")
merged_df

Cleaned, Integrated, and Transformed Data:


customer_id     name   age              email  order_id  product_id  \
0            1  Murshid  30.0  murshid@gmail.com       101         201   
1            2     Prem  25.0     prem@gmail.com       102         202   
2            3      Jon  40.0      jon@gmail.com       103         203   
3            4    Rahul  32.5    rahul@gmail.com       104         204   
4            5     Adil  35.0                N/A       105         205   

   quantity product_name  price  total_price Feed_back  
0         2       Laptop   1000         2000      Good  
1         1        Mouse     20           20       Bad  
2         3     Keyboard     50          150      Good  
3         2      Monitor    300          600      Good  
4         1      Printer    200          200       Bad

In [6]:
from sklearn.preprocessing import OrdinalEncoder, LabelEncoder
ordinal_encoder = OrdinalEncoder()
label_encode = LabelEncoder()

merged_ordinal_encoded = ordinal_encoder.fit_transform(merged_df)
feed_back_encoded = label_encode.fit_transform(merged_df['Feed_back'])

In [7]:
print("Features \n",merged_ordinal_encoded)
print("Target \n",feed_back_encoded)

Features 
 [[0. 2. 1. 2. 0. 0. 1. 1. 4. 4. 1.]
 [1. 3. 0. 3. 1. 1. 0. 3. 0. 0. 0.]
 [2. 1. 4. 1. 2. 2. 2. 0. 1. 1. 1.]
 [3. 4. 2. 4. 3. 3. 1. 2. 3. 3. 1.]
 [4. 0. 3. 0. 4. 4. 0. 4. 2. 2. 0.]]
Target 
 [1 0 1 1 0]
